name: Deploy Migrations to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci --legacy-peer-deps

      - name: Generate Prisma client
        working-directory: backend
        run: npx prisma generate --schema=prisma/schema.prisma

      - name: Apply database migrations
        working-directory: backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy --schema=prisma/schema.prisma
